name: Linter
on:
  pull_request:
  push:
    branches: [master]
jobs:
  eslint:
    name: esLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run esLint
        run: npm run lint
